{
 "title": "Analytics - NGINX / LOKI v2+ Data Source / Promtail v2+ Tool",
 "description": "Nginx access log analytics dashboard using Promtail and Loki v2+. Prometheus datasource is created from Loki service.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values({job=\"nginx\"}, host)"
   },
   {
    "name": "filename",
    "label": "filename",
    "query": "label_values({job=\"nginx\"}, filename)"
   },
   { "name": "job", "label": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "Unique user visits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(sum by (remote_addr) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | remote_addr !~ \"2001:4ca0:108:42::*\" | remote_addr !=\"62.210.149.41\" | remote_addr !~ \"91.134.156.*\" | remote_addr !~ \"37.59.149.*\" | http_user_agent != \"worldping-api\" | request_uri !~ \"/wp-.*\" | request_uri !~ \"//wp-.*\" | request_uri !~ \"/*.wordfence.*\" | request_uri !~ \"/robots.txt\" | request_uri !~ \"/xmlrpc.php\" | remote_addr != `217.131.101.19` | __error__=\"\" [1h])))"
    }
   ]
  },
  {
   "title": "Unique user visits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n    {filename=\"$filename\", host=\"$host\"}\r\n    | json\r\n    | http_user_agent !~ \".*bot.*\"\r\n    | http_user_agent !~ \".*crawler.*\"\r\n    | remote_addr !~ \"2001:4ca0:108:42::*\"\r\n    | remote_addr != \"62.210.149.41\"\r\n    | remote_addr != \"172.21.0.2\"\r\n    | remote_addr !~ \"91.134.156.*\"\r\n    | remote_addr !~ \"37.59.149.*\"\r\n    | http_user_agent != \"worldping-api\"\r\n    | request_uri !~ \"/wp-.*\"\r\n    | request_uri !~ \"//wp-.*\"\r\n    | request_uri !~ \"/.*wordfence.*\"\r\n    | request_uri !~ \"/robots.txt\"\r\n    | request_uri !~ \"/xmlrpc.php\"\r\n    | remote_addr != `217.131.101.19`\r\n    | __error__=\"\"\r\n    [24h]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Unique user visits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n    {filename=\"$filename\", host=\"$host\"}\r\n    | json\r\n    | http_user_agent !~ \".*bot.*\"\r\n    | http_user_agent !~ \".*crawler.*\"\r\n    | remote_addr !~ \"2001:4ca0:108:42::*\"\r\n    | remote_addr != \"62.210.149.41\"\r\n    | remote_addr != \"172.21.0.2\"\r\n    | remote_addr !~ \"91.134.156.*\"\r\n    | remote_addr !~ \"37.59.149.*\"\r\n    | http_user_agent != \"worldping-api\"\r\n    | request_uri !~ \"/wp-.*\"\r\n    | request_uri !~ \"//wp-.*\"\r\n    | request_uri !~ \"/.*wordfence.*\"\r\n    | request_uri !~ \"/robots.txt\"\r\n    | request_uri !~ \"/xmlrpc.php\"\r\n    | __error__=\"\"\r\n    [24h]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Unique user visits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n    {filename=\"$filename\", host=\"$host\"}\r\n    | json\r\n    | http_user_agent !~ \".*bot.*\"\r\n    | http_user_agent !~ \".*crawler.*\"\r\n    | remote_addr !~ \"2001:4ca0:108:42::*\"\r\n    | remote_addr != \"62.210.149.41\"\r\n    | remote_addr != \"172.21.0.2\"\r\n    | remote_addr !~ \"91.134.156.*\"\r\n    | remote_addr !~ \"37.59.149.*\"\r\n    | http_user_agent != \"worldping-api\"\r\n    | request_uri !~ \"/wp-.*\"\r\n    | request_uri !~ \"//wp-.*\"\r\n    | request_uri !~ \"/.*wordfence.*\"\r\n    | request_uri !~ \"/robots.txt\"\r\n    | request_uri !~ \"/xmlrpc.php\"\r\n    | __error__=\"\"\r\n    [24h]\r\n  )\r\n)"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (geoip_country_code) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | remote_addr !~ \"2001:4ca0:108:42::*\" | remote_addr !=\"62.210.149.41\" | remote_addr !~ \"91.134.156.*\" | remote_addr !~ \"37.59.149.*\" | http_user_agent != \"worldping-api\" | request_uri !~ \"/wp-.*\" | request_uri !~ \"//wp-.*\" | request_uri !~ \"/*.wordfence.*\" | request_uri !~ \"/robots.txt\" | request_uri !~ \"/xmlrpc.php\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Visitor Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unique user visits",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(sum by (remote_addr) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | remote_addr !~ \"2001:4ca0:108:42::*\" | remote_addr !=\"62.210.149.41\" | remote_addr !~ \"91.134.156.*\" | remote_addr !~ \"37.59.149.*\" | http_user_agent != \"worldping-api\" | request_uri !~ \"/wp-.*\" | request_uri !~ \"//wp-.*\" | request_uri !~ \"/*.wordfence.*\" | request_uri !~ \"/robots.txt\" | request_uri !~ \"/xmlrpc.php\" |  __error__=\"\" [1d])))",
       "legendFormat": "Unique user visit count"
      }
     ]
    },
    {
     "title": "Unique user visits",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(sum by (remote_addr) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | remote_addr !~ \"2001:4ca0:108:42::*\" | remote_addr !=\"62.210.149.41\" | remote_addr !~ \"91.134.156.*\" | remote_addr !~ \"37.59.149.*\" | http_user_agent != \"worldping-api\" | request_uri !~ \"/wp-.*\" | request_uri !~ \"//wp-.*\" | request_uri !~ \"/*.wordfence.*\" | request_uri !~ \"/robots.txt\" | request_uri !~ \"/xmlrpc.php\" |  __error__=\"\" [1d])))",
       "legendFormat": "Unique user visit count"
      }
     ]
    }
   ]
  },
  { "title": "Sources & Behaviours", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 27, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(\r\n  5,\r\n  sum by (remote_addr) (\r\n    count_over_time(\r\n      {filename=\"$filename\", host=\"$host\"}\r\n      | json\r\n      | http_user_agent !~ \".*bot.*\"\r\n      | http_user_agent !~ \".*crawler.*\"\r\n      | remote_addr !~ \"2001:4ca0:108:42::*\"\r\n      | remote_addr != \"62.210.149.41\"\r\n      | remote_addr != \"172.21.0.2\"\r\n      | remote_addr != \"172.21.0.3\"\r\n      | remote_addr !~ \"91.134.156.*\"\r\n      | remote_addr !~ \"37.59.149.*\"\r\n      | http_user_agent != \"worldping-api\"\r\n      | request_uri !~ \"/wp-.*\"\r\n      | request_uri !~ \"//wp-.*\"\r\n      | request_uri !~ \"/*.wordfence.*\"\r\n      | request_uri !~ \"/robots.txt\"\r\n      | request_uri !~ \"/xmlrpc.php\"\r\n      | remote_addr != `217.131.101.19`\r\n      | __error__=\"\"\r\n      [$__interval]\r\n    )\r\n  )\r\n)",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top HTTP Referers - Exclude Panxora Site",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_referer) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | http_user_agent != \"worldping-api\" | http_referer != \"\" and http_referer !~ \".*?$host.*?\" | http_referer !~ \".*?panxora.*?\" | http_referer != \"http://192.168.120.55:9000/\" | __error__=\"\" [$__interval]))) ",
     "legendFormat": "{{http_referer}}"
    }
   ]
  },
  {
   "title": "Top Requested Pages - Excluding '/'",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10,sum by (request_uri) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | request_uri != \"/\" | request_uri !~ \"/wp-.*\" | request_uri !~ \"//wp-.*\" | request_uri !~ \"/*.wordfence.*\" | request_uri !~ \"/robots.txt\" | request_uri !~ \"/xmlrpc.php\" | remote_addr != `217.131.101.19` | __error__=\"\" [$__interval])))",
     "legendFormat": "{{request_uri}}"
    }
   ]
  },
  {
   "title": "Top HTTP Referers",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 28 },
   "targets": [
    {
     "expr": "topk(5, sum by (http_referer) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | http_user_agent != \"worldping-api\" | http_referer != \"\" and http_referer !~ \".*?$host.*?\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_referer}}"
    }
   ]
  },
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 34 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_user_agent) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | http_user_agent != \"worldping-api\" |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_user_agent}}"
    }
   ]
  },
  { "title": "Requests & HTTP Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (status) (count_over_time({filename=\"$filename\", host=\"$host\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({filename=\"$filename\", host=\"$host\"}[$__interval]))  "
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum(rate({filename=\"$filename\", host=\"$host\"} | json | status >= 500 |__error__=\"\"[$__interval])) / (sum(rate({filename=\"$filename\", host=\"$host\"} | json | __error__=\"\"[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "% of requests by Googlebot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " sum(rate(({job=\"$job\", host=\"$host\"} |= \"Googlebot\")[$__interval])) / (sum(rate(({job=\"$job\", host=\"$host\"} != \"Googlebot\")[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({filename=\"$filename\", host=\"$host\"} | json | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"$filename\", host=\"$host\"}\r\n| json \r\n| http_user_agent !~ `.*bot.*`\r\n| http_user_agent !~ `.*crawler.*`\r\n| remote_addr !~ `2001:4ca0:108:42::*`\r\n| remote_addr != `62.210.149.41`\r\n| remote_addr != `172.21.0.2`\r\n| remote_addr != `172.21.0.3`\r\n| remote_addr !~ `91.134.156.*`\r\n| remote_addr !~ `37.59.149.*`\r\n| http_user_agent != `worldping-api`\r\n| request_uri !~ `^/api/`\r\n| request_uri !~ `^/public/plugins/`\r\n| request_uri != `/livereload.js`\r\n| request_uri !~ `^/wp-`\r\n| request_uri != `/robots.txt`\r\n| request_uri != `/xmlrpc.php`\r\n| remote_addr != `217.131.101.19`\r\n| line_format `{{if eq .status \"200\"}}🟢{{else if eq .status \"201\"}}🟢{{else if eq .status \"301\"}}🟡{{else if eq .status \"302\"}}🟡{{else if eq .status \"304\"}}🟡{{else if eq .status \"400\"}}🟠{{else if eq .status \"401\"}}🟠{{else if eq .status \"403\"}}🟠{{else if eq .status \"404\"}}🟠{{else if eq .status \"500\"}}🔴{{else if eq .status \"502\"}}🔴{{else if eq .status \"503\"}}🔴{{else}}⚪{{end}} {{.status}} | 🌐 {{.remote_addr}} | {{.request_uri}}`"
    }
   ]
  },
  {
   "title": "Request Statistics Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "95th percentile of Request Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "quantile_over_time(0.95,{filename=\"$filename\", host=\"$host\"} | json | unwrap request_time |  __error__=\"\"  [$__interval]) by (host)",
       "legendFormat": "95th percentile"
      },
      {
       "expr": "max by (host) (max_over_time({filename=\"$filename\", host=\"$host\"} | json | unwrap request_time |  __error__=\"\"  [$__interval]))",
       "legendFormat": "max latency"
      }
     ]
    },
    {
     "title": "HTTP requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 7, "y": 69 },
     "targets": [
      {
       "expr": "sum by (status) (count_over_time({filename=\"$filename\", host=\"$host\"} | json |  __error__=\"\" [$__interval]))",
       "legendFormat": "HTTP Status {{status}}"
      }
     ]
    },
    {
     "title": "Bytes Sent",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 69 },
     "targets": [
      {
       "expr": "sum by (host) (sum_over_time({filename=\"$filename\", host=\"$host\"} | json | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
       "legendFormat": "Bytes sent"
      }
     ]
    }
   ]
  }
 ]
}